### ISSUE TITLE
exemplar_method param for getting golden score

### ISSUE THREAD

**Issue by zahramahani** [pldlgb/nuggets#1]
would you please explain arguments that u have defined for producing golden scores?

exemplar_method : please talk about its 3 options stratified,random,written
pace
start
num_k_shot
and 
kv_itr

**Comment by pldlgb** [comment]
exemplar_method : only the 'stratified' parameter is available, we will refine the code later.
start:  starting index of instruction data
pace: start+pace = end (ending index of instruction data)
num_k_shot : default = 1, one shot learning
kv_itr: default=1 Perform kv_itr times meta-optimization on a one-shot prompt.
