### ISSUE TITLE
Question for Golden Scoring

### ISSUE THREAD

**Issue by cswangxiaowei** [pldlgb/nuggets#4]
I encounter the issues below when saving for Golden Scoring. 
![4371707716239_ pic](https://github.com/pldlgb/nuggets/assets/145024452/08a97779-341c-4dd1-a7b3-9af3351e652f)
May I know if I need to follow the readme inside "save" folder to create the required file? 
Thank you!

**Comment by pldlgb** [comment]
You should create the “score” folder inside save folder. We will check whether the folder exists later.
