### ISSUE TITLE
Keyword arguments {'add_special_tokens': False} not recognized. 

### ISSUE THREAD

**Issue by cswangxiaowei** [pldlgb/nuggets#6]
When I ran training process for Llama2-7b-hf, I encountered the following error:
Keyword arguments {'add_special_tokens': False} not recognized.

May I know how to solve this problem?
Thank you!

**Comment by LLLLLLutianxin** [comment]
You can update all the pip packages again, I encountered the same error, it was solved like this, I hope it can help you
