### ISSUE TITLE
关于exemplar_kv的一个问题

### ISSUE THREAD

**Issue by xikaluo** [pldlgb/nuggets#8]
您好，谢谢您提供的代码，我在阅读代码的过程中有一个问题，希望能得到解答：

在instruction_main.py的第193行，代码从待筛选的数据集中选出一条数据，进行forward并拿到past_key_value，然后在206行又将这个past_key_value传入do_infer_probs，并且也最终参与到模型的forward方法中。我有些疑惑的点是：
1. 这里的past_key_values是否仅仅为了提升速度？
2. 我发现在第81行如果不传入past_key_values，最终的分数会有变化，请问这是正常的吗？

希望能得到您的解答，谢谢～

**Comment by pldlgb** [comment]
您好，感谢您对我们工作的关注！
这里的past_key_value计算的是intruction样本的key和value，这样我们do_infer_probs中对很多predefined tasks 进行拼接infer的时候就不需要重复计算intruction的key和value了，确实可以提升运行的速度；如果你不传入past_key_values，那就没有instruction的信息了（也就是论文中的One Shot），所以分数变化是很正常的
